services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  earthquake_ingestor:
    build: .
    container_name: earthquake_ingestor
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    #volumes:
     # - .:/app
    working_dir: /app
    command: ["python", "-u", "ingestion/main.py"]

volumes:
  mysql_data:
